name: analyst_app
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  shared_preferences: ^0.4.2
  fluttertoast: ^3.1.0
  intl: ^0.15.8
  async_loader: ^0.1.1
  http: 0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/Nunito.ttf